"""
Parameters for server
"""

# in bytes
from asyncio.windows_events import NULL


CHUNK_SIZE = 1024
REQUEST_HEADER_SIZE = 23  # y
RESPONSE_HEADER_SIZE = 7  # y
MAX_USERNAME = 255  # y
MAX_FILENAME = 255
UUID_SIZE = 16  # y
MSG_TYPE_SIZE = 1
CONTENT_SIZE = 4
CKSUM_SIZE = 4


DEFUALT_PORT = 1234  # y
SERVER_DB = 'server.db'  # y
SERVER_VERSION = 3  # y
MAX_CONNECTIONS = 100  # y
IV = b'0000000000000000'  # '\0'  # check...
LEN_AES = 16  # y

# register request
REGISTER_REQUEST_CODE = 1100  # y
REGISTER_SUCCESS = 2100  # y
REGISTER_NOT_SUCCESS = 2101  # y

# public key request
CLIENTS_SEND_PUBLIC_KEY = 1101  # y
PUBLIC_KEY_SIZE = 160  # y
PUBLIC_KEY_REQUEST_PAYLOAD = MAX_USERNAME + PUBLIC_KEY_SIZE
PUBLIC_KEY_RESPOND_STATUS = 2102  # y

# sending incripted file
CLIENTS_SEND_ENCRYPTED_FILE = 1103  # y
CRC_SUCCESS = 1104  # y
CRC_FAILED = 1105  # y
CRC_FAILED_END_PROGRAM = 1106  # y
CRC_RESPOND_STATUS = 2103  # y

SUCCESS_MSG = 2104  # y
EMPTY_PAYLOAD = 0  # y

SERVER_ERROR_CODE = 9000
SERVER_ERROR_SIZE = 0

CRC_RESPONSE_PAYLOAD = UUID_SIZE + CONTENT_SIZE + MAX_FILENAME + CKSUM_SIZE
